// WorkLog Model - Track task-level work hours automatically
import mongoose, { Schema, Document } from 'mongoose'

export enum WorkLogType {
    CLOCK_IN = 'CLOCK_IN',
    CLOCK_OUT = 'CLOCK_OUT',
    BREAK_START = 'BREAK_START',
    BREAK_END = 'BREAK_END',
    TASK_START = 'TASK_START',
    TASK_END = 'TASK_END',
}

export interface IWorkLog extends Document {
    userId: string
    userName: string
    projectId: string
    taskId?: string
    machineId?: string
    type: WorkLogType
    timestamp: Date
    location?: {
        lat: number
        lng: number
        accuracy?: number
    }
    notes?: string
    autoGenerated: boolean
    deviceInfo?: string
    createdAt: Date
}

const WorkLogSchema = new Schema<IWorkLog>(
    {
        userId: { type: String, required: true, index: true },
        userName: { type: String, required: true },
        projectId: { type: String, required: true, index: true },
        taskId: { type: String, index: true },
        machineId: { type: String },
        type: {
            type: String,
            enum: Object.values(WorkLogType),
            required: true,
        },
        timestamp: { type: Date, required: true },
        location: {
            lat: Number,
            lng: Number,
            accuracy: Number,
        },
        notes: { type: String },
        autoGenerated: { type: Boolean, default: false },
        deviceInfo: { type: String },
    },
    { timestamps: true }
)

WorkLogSchema.index({ userId: 1, timestamp: -1 })
WorkLogSchema.index({ projectId: 1, timestamp: -1 })
WorkLogSchema.index({ userId: 1, projectId: 1, timestamp: -1 })

export const WorkLog = mongoose.models.WorkLog ||
    mongoose.model<IWorkLog>('WorkLog', WorkLogSchema)
